"""Comment.is_deleted added

Revision ID: 46042011c45b
Revises: 61e23f846820
Create Date: 2024-03-01 12:57:29.616243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46042011c45b'
down_revision: Union[str, None] = '61e23f846820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'is_deleted')
    # ### end Alembic commands ###
