"""picture update 1

Revision ID: 99a680a161a1
Revises: de6f3e056d51
Create Date: 2024-03-06 14:05:50.492855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a680a161a1'
down_revision: Union[str, None] = 'de6f3e056d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pictures', 'is_deleted')
    # ### end Alembic commands ###
