"""Transformed picture model

Revision ID: a8b392656524
Revises: d331b88858af
Create Date: 2024-03-06 12:27:54.193457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b392656524'
down_revision: Union[str, None] = 'd331b88858af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transformed_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('picture_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['picture_id'], ['pictures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformed_pictures_id'), 'transformed_pictures', ['id'], unique=False)
    op.add_column('qrcodes', sa.Column('transformed_picture_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'qrcodes', 'transformed_pictures', ['transformed_picture_id'], ['id'], ondelete='CASCADE')
    op.drop_column('qrcodes', 'transformed_photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qrcodes', sa.Column('transformed_photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'qrcodes', type_='foreignkey')
    op.drop_column('qrcodes', 'transformed_picture_id')
    op.drop_index(op.f('ix_transformed_pictures_id'), table_name='transformed_pictures')
    op.drop_table('transformed_pictures')
    # ### end Alembic commands ###
