"""update

Revision ID: b41c9ff29587
Revises: 6c2778c85d1b
Create Date: 2024-03-09 20:37:47.926852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b41c9ff29587'
down_revision: Union[str, None] = '6c2778c85d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_qrcodes_id', table_name='qrcodes')
    op.drop_table('qrcodes')
    op.drop_index('ix_transformed_pictures_id', table_name='transformed_pictures')
    op.drop_table('transformed_pictures')
    op.add_column('pictures', sa.Column('qr_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token')
    op.drop_column('pictures', 'qr_url')
    op.create_table('transformed_pictures',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('transformed_pictures_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('picture_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['picture_id'], ['pictures.id'], name='transformed_pictures_picture_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='transformed_pictures_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_transformed_pictures_id', 'transformed_pictures', ['id'], unique=False)
    op.create_table('qrcodes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transformed_picture_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['transformed_picture_id'], ['transformed_pictures.id'], name='qrcodes_transformed_picture_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='qrcodes_pkey')
    )
    op.create_index('ix_qrcodes_id', 'qrcodes', ['id'], unique=False)
    # ### end Alembic commands ###
