"""users

Revision ID: d3da806086b2
Revises: 358bc8202d18
Create Date: 2024-03-07 20:23:47.899896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3da806086b2'
down_revision: Union[str, None] = '358bc8202d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.add_column('pictures', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pictures', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pictures', type_='foreignkey')
    op.drop_column('pictures', 'user_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
